# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from nameplate.proto import nameplate_pb2 as nameplate_dot_proto_dot_nameplate__pb2


class NameplateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNameplate = channel.unary_unary(
        '/Nameplate/GetNameplate',
        request_serializer=nameplate_dot_proto_dot_nameplate__pb2.NameplateNumber.SerializeToString,
        response_deserializer=nameplate_dot_proto_dot_nameplate__pb2.NameplateNumber.FromString,
        )


class NameplateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetNameplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NameplateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNameplate': grpc.unary_unary_rpc_method_handler(
          servicer.GetNameplate,
          request_deserializer=nameplate_dot_proto_dot_nameplate__pb2.NameplateNumber.FromString,
          response_serializer=nameplate_dot_proto_dot_nameplate__pb2.NameplateNumber.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Nameplate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
