# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nameplate/proto/nameplate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nameplate/proto/nameplate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fnameplate/proto/nameplate.proto\" \n\x0fNameplateNumber\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x41\n\tNameplate\x12\x34\n\x0cGetNameplate\x12\x10.NameplateNumber\x1a\x10.NameplateNumber\"\x00\x62\x06proto3')
)




_NAMEPLATENUMBER = _descriptor.Descriptor(
  name='NameplateNumber',
  full_name='NameplateNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='NameplateNumber.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['NameplateNumber'] = _NAMEPLATENUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameplateNumber = _reflection.GeneratedProtocolMessageType('NameplateNumber', (_message.Message,), {
  'DESCRIPTOR' : _NAMEPLATENUMBER,
  '__module__' : 'nameplate.proto.nameplate_pb2'
  # @@protoc_insertion_point(class_scope:NameplateNumber)
  })
_sym_db.RegisterMessage(NameplateNumber)



_NAMEPLATE = _descriptor.ServiceDescriptor(
  name='Nameplate',
  full_name='Nameplate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNameplate',
    full_name='Nameplate.GetNameplate',
    index=0,
    containing_service=None,
    input_type=_NAMEPLATENUMBER,
    output_type=_NAMEPLATENUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAMEPLATE)

DESCRIPTOR.services_by_name['Nameplate'] = _NAMEPLATE

# @@protoc_insertion_point(module_scope)
