# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/stock/proto/stock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/stock/proto/stock.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n services/stock/proto/stock.proto\"#\n\x0bStockSymbol\x12\x14\n\x0cstock_symbol\x18\x01 \x01(\t\"\xb3\x01\n\x0cStockHistory\x12/\n\rstock_history\x18\x01 \x03(\x0b\x32\x18.StockHistory.StockPrice\x1ar\n\nStockPrice\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04open\x18\x03 \x01(\x01\x12\r\n\x05\x63lose\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\x0c\n\x04high\x18\x06 \x01(\x01\x12\x0e\n\x06volume\x18\x07 \x01(\x01\x32\x39\n\x05Stock\x12\x30\n\x0fGetStockHistory\x12\x0c.StockSymbol\x1a\r.StockHistory\"\x00\x62\x06proto3')
)




_STOCKSYMBOL = _descriptor.Descriptor(
  name='StockSymbol',
  full_name='StockSymbol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_symbol', full_name='StockSymbol.stock_symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=71,
)


_STOCKHISTORY_STOCKPRICE = _descriptor.Descriptor(
  name='StockPrice',
  full_name='StockHistory.StockPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='StockHistory.StockPrice.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='StockHistory.StockPrice.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='StockHistory.StockPrice.open', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='StockHistory.StockPrice.close', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='StockHistory.StockPrice.low', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='StockHistory.StockPrice.high', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='StockHistory.StockPrice.volume', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=253,
)

_STOCKHISTORY = _descriptor.Descriptor(
  name='StockHistory',
  full_name='StockHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock_history', full_name='StockHistory.stock_history', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STOCKHISTORY_STOCKPRICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=253,
)

_STOCKHISTORY_STOCKPRICE.containing_type = _STOCKHISTORY
_STOCKHISTORY.fields_by_name['stock_history'].message_type = _STOCKHISTORY_STOCKPRICE
DESCRIPTOR.message_types_by_name['StockSymbol'] = _STOCKSYMBOL
DESCRIPTOR.message_types_by_name['StockHistory'] = _STOCKHISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockSymbol = _reflection.GeneratedProtocolMessageType('StockSymbol', (_message.Message,), {
  'DESCRIPTOR' : _STOCKSYMBOL,
  '__module__' : 'services.stock.proto.stock_pb2'
  # @@protoc_insertion_point(class_scope:StockSymbol)
  })
_sym_db.RegisterMessage(StockSymbol)

StockHistory = _reflection.GeneratedProtocolMessageType('StockHistory', (_message.Message,), {

  'StockPrice' : _reflection.GeneratedProtocolMessageType('StockPrice', (_message.Message,), {
    'DESCRIPTOR' : _STOCKHISTORY_STOCKPRICE,
    '__module__' : 'services.stock.proto.stock_pb2'
    # @@protoc_insertion_point(class_scope:StockHistory.StockPrice)
    })
  ,
  'DESCRIPTOR' : _STOCKHISTORY,
  '__module__' : 'services.stock.proto.stock_pb2'
  # @@protoc_insertion_point(class_scope:StockHistory)
  })
_sym_db.RegisterMessage(StockHistory)
_sym_db.RegisterMessage(StockHistory.StockPrice)



_STOCK = _descriptor.ServiceDescriptor(
  name='Stock',
  full_name='Stock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=255,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStockHistory',
    full_name='Stock.GetStockHistory',
    index=0,
    containing_service=None,
    input_type=_STOCKSYMBOL,
    output_type=_STOCKHISTORY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCK)

DESCRIPTOR.services_by_name['Stock'] = _STOCK

# @@protoc_insertion_point(module_scope)
