# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/alpr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/alpr.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10proto/alpr.proto\"\x1b\n\tALPRChunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x1e\n\x0c\x41LPRAnalysis\x12\x0e\n\x06plates\x18\x01 \x03(\t\"-\n\x0b\x41LPRResults\x12\x1e\n\x07results\x18\x01 \x03(\x0b\x32\r.ALPRAnalysis28\n\x0e\x41LPRFileServer\x12&\n\x06upload\x12\n.ALPRChunk\x1a\x0c.ALPRResults\"\x00(\x01\x62\x06proto3')
)




_ALPRCHUNK = _descriptor.Descriptor(
  name='ALPRChunk',
  full_name='ALPRChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='ALPRChunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_ALPRANALYSIS = _descriptor.Descriptor(
  name='ALPRAnalysis',
  full_name='ALPRAnalysis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plates', full_name='ALPRAnalysis.plates', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)


_ALPRRESULTS = _descriptor.Descriptor(
  name='ALPRResults',
  full_name='ALPRResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='ALPRResults.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=126,
)

_ALPRRESULTS.fields_by_name['results'].message_type = _ALPRANALYSIS
DESCRIPTOR.message_types_by_name['ALPRChunk'] = _ALPRCHUNK
DESCRIPTOR.message_types_by_name['ALPRAnalysis'] = _ALPRANALYSIS
DESCRIPTOR.message_types_by_name['ALPRResults'] = _ALPRRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ALPRChunk = _reflection.GeneratedProtocolMessageType('ALPRChunk', (_message.Message,), {
  'DESCRIPTOR' : _ALPRCHUNK,
  '__module__' : 'proto.alpr_pb2'
  # @@protoc_insertion_point(class_scope:ALPRChunk)
  })
_sym_db.RegisterMessage(ALPRChunk)

ALPRAnalysis = _reflection.GeneratedProtocolMessageType('ALPRAnalysis', (_message.Message,), {
  'DESCRIPTOR' : _ALPRANALYSIS,
  '__module__' : 'proto.alpr_pb2'
  # @@protoc_insertion_point(class_scope:ALPRAnalysis)
  })
_sym_db.RegisterMessage(ALPRAnalysis)

ALPRResults = _reflection.GeneratedProtocolMessageType('ALPRResults', (_message.Message,), {
  'DESCRIPTOR' : _ALPRRESULTS,
  '__module__' : 'proto.alpr_pb2'
  # @@protoc_insertion_point(class_scope:ALPRResults)
  })
_sym_db.RegisterMessage(ALPRResults)



_ALPRFILESERVER = _descriptor.ServiceDescriptor(
  name='ALPRFileServer',
  full_name='ALPRFileServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=128,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='ALPRFileServer.upload',
    index=0,
    containing_service=None,
    input_type=_ALPRCHUNK,
    output_type=_ALPRRESULTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALPRFILESERVER)

DESCRIPTOR.services_by_name['ALPRFileServer'] = _ALPRFILESERVER

# @@protoc_insertion_point(module_scope)
