# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from car.proto import car_pb2 as car_dot_proto_dot_car__pb2


class CarStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCar = channel.unary_unary(
        '/Car/GetCar',
        request_serializer=car_dot_proto_dot_car__pb2.Number.SerializeToString,
        response_deserializer=car_dot_proto_dot_car__pb2.Number.FromString,
        )


class CarServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CarServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCar': grpc.unary_unary_rpc_method_handler(
          servicer.GetCar,
          request_deserializer=car_dot_proto_dot_car__pb2.Number.FromString,
          response_serializer=car_dot_proto_dot_car__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Car', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
